### ISSUE TITLE
Update dependencies to resolve security vulnerabilities

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node-dashboard#2]
See issues discovered by dependabot https://github.com/Concordium/concordium-node-dashboard/security/dependabot

@limemloh

**Comment by concordium-cl** [comment]
What is the status on this, @limemloh?

**Comment by limemloh** [comment]
Last time I checked, we were waiting for one of our dependencies to update.
I'll check if this is still the case in a moment

**Comment by concordium-cl** [comment]
@limemloh: Please check again.

**Comment by limemloh** [comment]
The dependency (parcel) is including the fix in the next release, which is currently only available as a beta release.
But with the new plans for the node dashboard this dependency will most likely be replaced.

**Comment by concordium-cl** [comment]
Electron should not depend on that. Will close issue.

**Comment by abizjak** [comment]
Closing as per the last comment.
