### ISSUE TITLE
General issues/improvements

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node-dashboard#4]
* Baking information is not displayed when the node is a baker. This appears to be due to a change in the representation of credentials on accounts from a list to a map.

* Account information is not displayed when clicking on baker accounts.

* Block Explorer should be removed until the functionality is implemented.

* The warning time for received finalized block should not be displayed in millisecond accuracy.

* Warnings for failure to receive/finalize a block within a certain time should be relaxed. Suggest:

  - 5 minutes for block receipt. (With planned settings, this would happen about once in 1000 years coincidentally (if the bakers and network are fully operational).)

  - 10 minutes for block finalization.

* "Node only have 0 peers" -> "has"

* Copy to clipboard functionality does not work for account information or baker identities.

**Comment by concordium-cl** [comment]
Low priority for remaining issues after pr is merged.

@td202: Could you please make a checkbox list of the items to keep track which ones are remaining. Thx.

**Comment by td202** [comment]
All of these are either fixed by the PR, or were already fixed (but hadn't made it to the distribution).
